# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('manager', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.IntegerField(default=0)),
                ('active_user', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
