# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('online', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
    ]
