# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='code',
            field=models.CharField(default='ASDFG', max_length=200),
            preserve_default=False,
        ),
    ]
