# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('active', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='clerk',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 21, 11, 35, 33, 199000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 21, 11, 35, 37, 871000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='exhibition',
            field=models.CharField(default=12312312312312321321L, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 21, 11, 35, 58, 192000)),
            preserve_default=False,
        ),
    ]
