# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 07:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20161021_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='active_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 21, 15, 34, 12, 806000)),
            preserve_default=False,
        ),
    ]
