# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20161024_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='business_id',
            field=models.CharField(default=29, max_length=200),
            preserve_default=False,
        ),
    ]
