# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_sale_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('base', models.FloatField(default=0.0)),
                ('bonus', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
    ]
