# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20161027_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
