# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_cashrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='clerk',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clerk',
            name='base',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clerk',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clerk',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
