# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20161027_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleNano',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
