# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_shop_machine_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
