# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_shop_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrecord',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.CharField(max_length=400),
        ),
    ]
