# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_sale_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrecord',
            name='wechat',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
