# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_cashrecord_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrecord',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
