# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20161031_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='promotion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
