# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_sale_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='manager',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
