# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_auto_20161031_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='salenano',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salenano',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
