# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20161031_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='psw',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='psw',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
