# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_auto_20161102_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='benchmark1',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='benchmark2',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bonus1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bonus2',
            field=models.FloatField(default=0.0),
        ),
    ]
