# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_auto_20161104_1348'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='clerk',
        #     name='openid',
        #     field=models.CharField(blank=True, max_length=200),
        # ),
        # migrations.AddField(
        #     model_name='manager',
        #     name='area',
        #     field=models.CharField(blank=True, max_length=200),
        # ),
        # migrations.AddField(
        #     model_name='manager',
        #     name='name',
        #     field=models.CharField(blank=True, max_length=200),
        # ),
        migrations.AddField(
            model_name='shop',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        # migrations.AddField(
        #     model_name='store',
        #     name='openid',
        #     field=models.CharField(blank=True, max_length=200),
        # ),
    ]
