# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_clerk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=200)),
                ('clerk_id', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.IntegerField(default=0)),
            ],
        ),
    ]
