# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20161021_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='option',
        ),
    ]
