# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20161022_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='active_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
