# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_exhibition_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
