# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20161025_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='cashed',
            field=models.IntegerField(default=0),
        ),
    ]
