# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('base', models.FloatField(default=0.0)),
                ('bonus', models.FloatField(default=0.0)),
                ('money', models.FloatField(default=0.0)),
            ],
        ),
    ]
