# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20161030_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='agent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
