# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_shop_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='device_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
