# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_clerk_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='valid',
            field=models.IntegerField(default=0),
        ),
    ]
