# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_shop_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseCondition',
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
