# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_auto_20161102_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerk',
            old_name='psw',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='psw',
            new_name='pwd',
        ),
    ]
